project:
  name: quickstart-taskcat-ci
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  quickstart-taskcat-ci-test1:
    parameters:
      GitHubOAuthToken: override
      GitHubRepoName: override
      GitHubUser: aws-quickstart
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-taskcat-ci/
      ReleaseBranch: main
      SourceRepoBranch: develop
    regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    s3_bucket: ''
    template: templates/taskcat-ci-pipeline.template
